# Generated by Django 4.1.3 on 2022-11-10 10:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалено")),
            ],
            options={"verbose_name": "курс", "verbose_name_plural": "курсы",},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                (
                    "preamble",
                    models.CharField(max_length=1024, verbose_name="Вступление"),
                ),
                ("body", models.TextField(null=True, verbose_name="Содержимое")),
                (
                    "body_as_markdown",
                    models.BooleanField(
                        default=False, verbose_name="Разметка в формате Markdown"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалено")),
            ],
            options={"verbose_name": "новость", "verbose_name_plural": "новости",},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.PositiveIntegerField(default=0, verbose_name="Номер урока"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалено")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={"verbose_name": "урок", "verbose_name_plural": "уроки",},
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=256, verbose_name="Фамилия")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалено")),
                ("courses", models.ManyToManyField(to="mainapp.course")),
            ],
            options={
                "verbose_name": "курс к учителю",
                "verbose_name_plural": "курсы к учителям",
            },
        ),
    ]
