# Generated by Django 4.1.3 on 2022-12-08 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_course_created_at_alter_course_update_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefeedback",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
