# Generated by Django 4.1.3 on 2022-12-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_coursefeedback_created_alter_coursefeedback_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-id"],
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
            },
        ),
    ]
